### PR TITLE
Fix/style fixes

### LINKED ISSUE #915: Docs nav - Fixed brand box
Please can you apply a fixed position to the brand box in the Docs nav, the content should scroll below. I've included a link to the Figma component library which demonstrates the desired effect. Let me know if you have any questions or problems.

https://www.figma.com/design/fiRq7KxIGnqx6vuBuUwdM7/GUI3.0-Docs?node-id=0-4743&m=dev

### PR DESCRIPTION
**Pull request by HZ991**
Work in progress PR.
Includes following changes:
- progress indicator component upgrade #914
- protoform and ui style/visual bug fixes #915

### CODE REVIEW

**Review by jaortiz — CHANGES_REQUESTED** [review]
Also add more tests now progress indicator has more functionality

File: packages/ui/src/components/progress-indicator/progress-indicator.component.tsx [hunk 1]
```diff
@@ -1,21 +1,74 @@
...
 import { ProgressIndicatorProps } from './progress-indicator.types.js';
 
 export function ProgressIndicator({
-  className,
-  children,
-  color = 'hero',
+  inverted = false,
+  label,
   size = 'medium',
+  embedIcon: EmbedIcon,
```
[the remark this answers is not in the document]
Comment (HZ991) [reply packages/ui/src/components/progress-indicator/progress-indicator.component.tsx:13]: is icon: EmbedIcon ok, it is just conflicting with the other 'Icon' import

File: packages/ui/src/components/progress-indicator/progress-indicator.component.tsx [hunk 2]
```diff
@@ -1,21 +1,74 @@
...
 
-import { styles } from './progress-indicator.styles.js';
+import { styles as ProgressIndicatorStyles } from './progress-indicator.styles.js';
 import { ProgressIndicatorProps } from './progress-indicator.types.js';
 
 export function ProgressIndicator({
-  className,
-  children,
   color = 'hero',
+  inverted = false,
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.component.tsx:11]: Remove inverted since we are using color prop

File: packages/ui/src/components/progress-indicator/progress-indicator.component.tsx [hunk 3]
```diff
@@ -1,21 +1,74 @@
...
   return (
-    <Icon className={styles({ className })} size={size} color={color} aria-label={ariaLabel} {...props}>
-      {children}
-    </Icon>
+    <div aria-label={ariaLabel} className={styles.container()}>
+      <div className="relative">
+        <Icon
+          viewBox="0 0 180 180"
+          fill="none"
+          color={inverted ? 'white' : 'hero'}
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.component.tsx:42]: Update to pass `color` prop through

File: packages/ui/src/components/progress-indicator/progress-indicator.component.tsx [hunk 4]
```diff
@@ -1,21 +1,74 @@
...
+                d={`M ${strokeHalfWidth} 90 A ${90 - strokeHalfWidth} ${90 - strokeHalfWidth} 0 0 1 ${180 - strokeHalfWidth} 90`}
+              ></path>
+              <path
+                stroke={`url(#${id}-2)`}
+                d={`M ${180 - strokeHalfWidth} 90 A ${90 - strokeHalfWidth} ${90 - strokeHalfWidth} 0 0 1 ${strokeHalfWidth} 90`}
+              ></path>
+            </>
+          </g>
+        </Icon>
+        {EmbedIcon && size === 'large' && <EmbedIcon size="large" className={styles.icon()} />}
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.component.tsx:69]: Need to pass `color` prop through to the embedded icon here too

File: packages/ui/src/components/progress-indicator/progress-indicator.styles.ts [hunk 5]
```diff
@@ -2,7 +2,37 @@ import { tv } from 'tailwind-variants';
...
+        medium: { base: 'h-4 w-4' },
+        large: { base: 'h-15 w-15' },
+        xlarge: { base: 'h-15 w-15' },
+      },
+      inverted: {
+        true: '',
+        false: '',
+      },
+    },
+    compoundSlots: [
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.styles.ts:24]: Need to update to use the color prop to update the text color

File: packages/ui/src/components/progress-indicator/progress-indicator.types.ts [hunk 6]
```diff
@@ -1,3 +1,24 @@
...
+  children?: ReactNode;
+  /**
+   * Icon embedded in progress indicator
+   */
+  icon?: (props: IconProps) => JSX.Element;
+  /**
+   * Progress indicator color
+   * @default false
+   */
+  inverted?: boolean;
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.types.ts:19]: Remove inverted type

**Review by jaortiz — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/progress-indicator/progress-indicator.types.ts [hunk 7]
```diff
@@ -1,3 +1,19 @@
+import { ReactNode } from 'react';
+
 import { IconProps } from '../icon/icon.types.js';
 
-export type ProgressIndicatorProps = IconProps;
+export type ProgressIndicatorProps = IconProps & {
```
Comment (jaortiz) [inline packages/ui/src/components/progress-indicator/progress-indicator.types.ts:5]: Minor: Update to `Omit<IconProps, 'copyrightYear' | 'look'>`

**Review by jaortiz — APPROVED** [review]
